version: '3.8'

services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile  # pastikan Dockerfile ini berisi setup PHP-FPM untuk Laravel
    container_name: laravel-php-fpm
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - APP_KEY=${LARAVEL_APP_KEY}
      - DB_HOST=mysql
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret

  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf   # file konfigurasi nginx
    depends_on:
      - php-fpm

  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
