version: "3.8"

services:
  laravel-app:
    image: rifkirizkia/todolist-be:latest
    container_name: todolist-be
    ports:
      - "8000:80"  # akses Laravel di http://your-server-ip:8000
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
      - ./.env:/var/www/html/.env
    env_file:
      - ./.env
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: todolist-db

    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/todolist_db
    restart: unless-stoppedAdd commentMore actions

volumes:
  mysql_data: