name: CI/CD Laravel to Docker Hub & VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set short SHA
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/todolist-be:latest
            ${{ secrets.DOCKER_USERNAME }}/todolist-be:${{ env.SHORT_SHA }}

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            IMAGE="${{ secrets.DOCKER_USERNAME }}/todolist-be"
            VERSION=${{ env.SHORT_SHA }}
            
            echo "Stopping and removing existing container (if any)..."
            docker stop todolist-be || true
            
            echo "Pulling new image..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/todolist-be:${{ env.SHORT_SHA }}
            
            echo "Running new container..."
            docker run -d --name todolist-be -p 9000:9000 ${{ secrets.DOCKER_USERNAME }}/todolist-be:${{ env.SHORT_SHA }}

