name: CI/CD Laravel to Docker Hub & VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/todolist-be:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/todolist-be:latest

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            docker stop todolist-be || true
            docker rm todolist-be || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/todolist-be:latest
            docker run -d --name todolist-be -p 8000:8000 \
              -e APP_ENV=production \
              -e APP_KEY=${{ secrets.LARAVEL_APP_KEY }} \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_PORT=${{ secrets.DB_PORT }} \
              -e DB_DATABASE=${{ secrets.DB_DATABASE }} \
              -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -v /home/${{ secrets.SERVER_USER }}/laravel-storage:/var/www/storage \
              ${{ secrets.DOCKER_USERNAME }}/todolist-be:latest
            docker exec todolist-be php artisan migrate --force
